#!/usr/bin/env bash

set -euo pipefail

function main() {
    setup

    local credhub_ip credhub_port
    credhub_ip=$(own_spec_var /deployment_vars/credhub_ip0) # or credhub_ip1
    credhub_port=$(depl_var /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/port)

    echo "CREDHUB_CLIENT=\"credhub-admin\""
    echo "CREDHUB_SECRET=\"$(creds_var "/credhub-admin-client-secret")\""
    echo "CREDHUB_SERVER=\"https://${credhub_ip}:${credhub_port}\""
    echo "CREDHUB_CA_CERT=\"$(creds_var "/concourse-internal-ca/certificate")\""
}

function setup() {
    SUBSYS_DIR=${SUBSYS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
    cd "${SUBSYS_DIR}" || exit 115
    BASE_DIR=${BASE_DIR:-$(git rev-parse --show-toplevel)}
    SUBSYS_NAME=$(own_spec_var /subsys/name)
    readonly SUBSYS_DIR BASE_DIR SUBSYS_NAME
}

function own_spec_var() {
    local path=$1
    bosh int "${SUBSYS_DIR}/conf/spec.yml" --path "${path}"
}

function state_var() {
    local state_file=$1
    local path=$2
    bosh int "${BASE_DIR}/state/${SUBSYS_NAME}/${state_file}.yml" --path "${path}"
}

function creds_var() {
    state_var "depl-creds" "$1"
}

function depl_var() {
    state_var "depl-manifest" "$1"
}

main "$@"
